import streamlit as st
import pandas as pd
import os
from dotenv import load_dotenv
import google.generativeai as genai
from app.chat_engine import ChatEngine

# Load environment variables
load_dotenv()
API_KEY = os.getenv("GEMINI_API_KEY")
if API_KEY:
    genai.configure(api_key=API_KEY)

st.set_page_config(page_title="Spotify PM Review Discovery Engine", layout="wide")

st.title("📊 Spotify PM Review Discovery Engine")
st.markdown("Analyze user reviews and reddit discussions at scale to uncover discovery friction and repetitive listening behavior.")

# Load Data
@st.cache_data
def load_data():
    if os.path.exists('data/normalized_reviews.csv'):
        df = pd.read_csv('data/normalized_reviews.csv')
        df['date'] = pd.to_datetime(df['date'])
        return df
    return None

df = load_data()

if df is None:
    st.warning("No normalized data found. Please run the data collection scripts first.")
    st.stop()

# Sidebar Filters
st.sidebar.header("Filters")
sources = st.sidebar.multiselect("Select Source", options=df['source'].unique(), default=df['source'].unique())

min_date = df['date'].min().date()
max_date = df['date'].min().date()
# Fix for empty min/max date issues if df is somehow malformed
if pd.notnull(df['date'].min()):
    min_date = df['date'].min().date()
    max_date = df['date'].max().date()
    
date_range = st.sidebar.date_input("Select Date Range", value=(min_date, max_date), min_value=min_date, max_value=max_date)

# Apply Filters
if len(date_range) == 2:
    start_date, end_date = date_range
    start_date = pd.to_datetime(start_date)
    end_date = pd.to_datetime(end_date)
    filtered_df = df[(df['source'].isin(sources)) & (df['date'] >= start_date) & (df['date'] <= end_date)]
else:
    filtered_df = df[df['source'].isin(sources)]

tab1, tab2, tab3 = st.tabs(["Dashboard & Insights", "Ask the Reviews (AI Chat)", "Raw Data"])

with tab1:
    st.header("Dashboard Metrics")
    col1, col2, col3 = st.columns(3)
    col1.metric("Total Reviews Analyzed", len(filtered_df))
    col2.metric("Average Rating", round(filtered_df['rating'].mean(), 2))
    col3.metric("Feedback Sources Engaged", len(filtered_df['source'].unique()))
    
    st.subheader("Sentiment Trends (Average Rating over Time)")
    # Group by month/week
    trend_df = filtered_df.set_index('date').resample('ME')['rating'].mean().reset_index()
    st.line_chart(trend_df.set_index('date'))

    st.header("AI Analysis Report")
    st.markdown("This report is generated by Gemini based on the collected reviews, focusing on themes, JTBD, personas, and opportunities.")
    if os.path.exists('data/analysis_report.md'):
        with open('data/analysis_report.md', 'r', encoding='utf-8') as f:
            st.markdown(f.read())
    else:
        st.info("No AI analysis report found. Please run the pipeline script (`analysis/pipeline.py`).")

with tab2:
    st.header("Ask the Reviews (AI Chat)")
    st.markdown("Ask dynamic questions about the feedback! Examples: *'Why do users repeatedly listen to the same playlists?'*, *'Show all complaints about music discovery.'*")
    
    # Initialize chat engine in session state so history is preserved
    if "chat_engine" not in st.session_state:
        st.session_state.chat_engine = ChatEngine()
        
    if "messages" not in st.session_state:
        st.session_state.messages = []

    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    if prompt := st.chat_input("Ask a question about the reviews..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)
            
        with st.chat_message("assistant"):
            with st.spinner("Analyzing reviews..."):
                response = st.session_state.chat_engine.get_response(prompt, filtered_df)
                st.markdown(response)
        st.session_state.messages.append({"role": "assistant", "content": response})

with tab3:
    st.header("Raw Filtered Data")
    st.dataframe(filtered_df)
